// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc36RjbBZCoulJQmBdphvRbl94c37WrJA',
    appId: '1:774328912264:web:1a847668a8d07f3aec923d',
    messagingSenderId: '774328912264',
    projectId: 'compflow-3ebc1',
    authDomain: 'compflow-3ebc1.firebaseapp.com',
    storageBucket: 'compflow-3ebc1.firebasestorage.app',
    measurementId: 'G-YCR944FBNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-e48JlwuKxhcCNiqZbdwcVLXFxY3cek',
    appId: '1:774328912264:android:a657cae2b477116eec923d',
    messagingSenderId: '774328912264',
    projectId: 'compflow-3ebc1',
    storageBucket: 'compflow-3ebc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWub6M8AhwxWGSvStjj9lYmL8BiVnoQgI',
    appId: '1:774328912264:ios:b139e48b5127d016ec923d',
    messagingSenderId: '774328912264',
    projectId: 'compflow-3ebc1',
    storageBucket: 'compflow-3ebc1.firebasestorage.app',
    iosBundleId: 'com.example.compflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWub6M8AhwxWGSvStjj9lYmL8BiVnoQgI',
    appId: '1:774328912264:ios:b139e48b5127d016ec923d',
    messagingSenderId: '774328912264',
    projectId: 'compflow-3ebc1',
    storageBucket: 'compflow-3ebc1.firebasestorage.app',
    iosBundleId: 'com.example.compflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc36RjbBZCoulJQmBdphvRbl94c37WrJA',
    appId: '1:774328912264:web:eb3e6230e7cc9b1cec923d',
    messagingSenderId: '774328912264',
    projectId: 'compflow-3ebc1',
    authDomain: 'compflow-3ebc1.firebaseapp.com',
    storageBucket: 'compflow-3ebc1.firebasestorage.app',
    measurementId: 'G-B70439WTEP',
  );
}
